spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: "test-group"


comment:
  image:
    largeImageMaxSize: 1080
    smallImageMaxSize: 170

