spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
  liquibase:
    enabled: true
    contexts: test
    change-log: classpath:/db/changelog/db.changelog-test.yaml