spring:
  profiles:
    active: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/post-service
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel

topics:
  comment: "comment"

server:
  port: 8081
  servlet:
    context-path: /posts/api

logging:
  level:
    root: info

post:
  moderation:
    batch-size: 10
    page-size: 20
    cronPeriod: "0 0 0 * * *"
  schedule:
    batch-size: 1000
    scheduled-cron: "0 * * * * *"
    max-retries: 5
    timeout: 10
    initial-delay: 500
    delay-multiplier: 2
    batchCount: 3

thread:
  pool:
    size: 10

services:
  s3:
    endpoint: http://localhost:9000
    accessKey: user
    secretKey: password
    bucketName: postbucket
    max_image_size: 5

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

---

spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: info

---

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: info
