spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        comment-channel: comment_channel
        calculations_channel:
          name: calculations_channel

  mvc:
    servlet:
      path: /api/v1

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8081

  tomcat:
    max-swallow-size: 5MB

thread_pool:
  max_threads: 10

post_service:
  batch_size: 1000

logging:
  level:
    root: info
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080
ad-service:
  ad-removal:
    batch-size: 10
    cron: "0 0 0 * * ?"
    #Каждый день в 00:00
like-service:
  batch-size: 100

aws:
  url: http://localhost:9000
  user: user
  password: password
  bucketName: commentbucket

image:
  smallImageSize: 170
  largeImageSize: 1080

comment:
  path-to-dictionary: /bad_words_list.txt

  schedule:
    verify: "*/10 * * * * *"
    user-ban: "* */50 * * * * *"
  batchSize: 100
  thread-pool-size: 4
  word-split-regex: "(?<=\\p{L})(?=\\p{P})|(?<=\\p{P})(?=\\p{L})|\\s+"

